### PR TITLE
refactor #30

### PR DESCRIPTION
**Pull request by regislon**
# Prework

- [ x] I understand and agree to this repository's [code of conduct](https://github.com/ltelab/disdrodb/blob/main/CODE_OF_CONDUCT.md).
- [ x] I understand and agree to this repository's [contributing guidelines](https://github.com/ltelab/disdrodb/blob/main/CONTRIBUTING.md).
- [x ] I have already submitted an [issue](https://github.com/ltelab/disdrodb/issues) or [discussion thread](https://github.com/ltelab/disdrodb/discussions) to discuss my idea with the maintainers.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x ] No

If yes, please describe the impact and communicate accordingly:

**The PR fulfills these requirements:**

- [ x] It's submitted to the branch named as follow : 
  - Add a reader: `reader-<institute>-<campaign>`
  - Fix a bug: `bugfix-<some_key>-<word>`
  - Improve the doc: `doc-<some_key>-<word>`
  - Add a new feature: `feature-<some_key>-<word>`
  - Refactor some code: `refactor-<some_key>-<word>`
  - Optimize some code: `optimize-<some_key>-<word>`
- [x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ x] Don't forget to link PR to issue if you are solving one.
- [ ] All tests are passing.
- [ ] New/updated tests are included

# Related GitHub issues and pull requests

- Ref: #30

# Summary

Change have made accordingly to @ghiggi instructions

### CODE REVIEW

**Comment by ghiggi** [comment]
The refactor is correct @regislon. But at this point, I would also update the imports of all templates since you just did those for NCAR. When the level naming refactoring has been done, the imports of all templates weren't modified accordingly. So simply copy and paste the imports of a NCAR template in all the other templates.

**Comment by regislon** [comment]
Hi @ghiggi Ok for me. I'll do it.

**Comment by regislon** [comment]
Hi @ghiggi, I refactor all import statments in the templates folder. I also remove the used package, and I run black over the whole folder. 
I still have two questions before you approve this PR : 

**Q1**
from disdrodb.data_encodings import get_L0_dtype_standards

The get_L0_dtype_standards() does not require any argument. But disdrodb.l0.standards.get_L0A_dtype()has now one argument "sensor_name". do I need to add the sensor name to this function for all files ?

**Q2**

from disdrodb.standards import get_OTT_Parsivel_dict, get_OTT_Parsivel2_dict
get_OTT_Parsivel_dict does not exist, should be replaced by get_L0A_dtype('OTT_Parsivel') ?

Thank for your answers.

**Comment by ghiggi** [comment]
Thanks for taking care of that.  Most templates are very messy. It will be worth properly cleaning it out once we will have defined the basic template ;) 

**Q1**
We removed the `get_L0_dtype_standards `function and replaced it with` disdrodb.l0.standards.get_L0A_dtype`. 
Yes, you should pass the `sensor_name `argument. When I did the refactoring, I didn't update the templates. Sorry :( 

**Q2**
These imports and code lines are outdated and should be removed. I guess it would be the function [get_variables_dict](https://github.com/ltelab/disdrodb/blob/main/disdrodb/L0/standards.py#L80) now, but makes no sense to have it.

We can postpone such template changes if you want, and merge this PR already. Let me know

**Review by ghiggi — COMMENTED** [review]
@regislon LGTM

**Comment by regislon** [comment]
ok I added the issues #40 and  #41

**Comment by regislon** [comment]
@ghiggi you can merge the pull request

**Review by ghiggi — APPROVED** [review]

**Pull request merged**
