### PR TITLE
Doc refactor API section

### PR DESCRIPTION
**Pull request by regislon**
# Prework

- [x] I understand and agree to this repository's [code of conduct](https://github.com/ltelab/disdrodb/blob/main/CODE_OF_CONDUCT.md).
- [x] I understand and agree to this repository's [contributing guidelines](https://github.com/ltelab/disdrodb/blob/main/CONTRIBUTING.md).
- [x] I have already submitted an [issue](https://github.com/ltelab/disdrodb/issues) or [discussion thread](https://github.com/ltelab/disdrodb/discussions) to discuss my idea with the maintainers.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and communicate accordingly:

**The PR fulfills these requirements:**

- [x] It's submitted to the branch named as follow : 
  - Add a reader: `reader-<institute>-<campaign>`
  - Fix a bug: `bugfix-<some_key>-<word>`
  - Improve the doc: `doc-<some_key>-<word>`
  - Add a new feature: `feature-<some_key>-<word>`
  - Refactor some code: `refactor-<some_key>-<word>`
  - Optimize some code: `optimize-<some_key>-<word>`
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] Don't forget to link PR to issue if you are solving one.
- [x] All tests are passing.
- [x] New/updated tests are included

**Other information:**

# Related GitHub issues and pull requests

- Ref: #125 

# Summary

Refactor the API section of the doc. See [the dev doc to view the results](https://disdrodb-dev.readthedocs.io/en/latest/).

### CODE REVIEW

**Review by charlottegiseleweil — CHANGES_REQUESTED** [review]
@ghiggi @regislon ok to remove setup.py from doc.

However, I don't understand the justification of removing the documentation for the pipeline scripts. 
 - Is "pipeline" a temp folder for temporary work ? If so, shouldn't be there (should be a branch)
 - Is "pipeline" useful code ? If so, should be documented.

**Comment by ghiggi** [comment]
I agree with @charlottegiseleweil that the pipeline folder should/could be removed. 
It contains scripts we launch on our server to generate all the DISDRODB archives, but these should not be included in the main repository in the long run.

**Comment by regislon** [comment]
@charlottegiseleweil could you treat this please ?

**Review by charlottegiseleweil — APPROVED** [review]
Lgtm thanks for the edits ! 

- @regislon sorry for the late reply - I did not get notified because it looks like you need to "re-request review" if changes were requested in the first review :o

**Comment by ghiggi** [comment]
Remove any reference to the `pipeline` and the `pipeline` directory before merging please ;)

**Comment by regislon** [comment]
merged

**Pull request merged**
