### PR TITLE
Feat: add lint to CI (Ruff and Black)

### PR DESCRIPTION
**Pull request by sphamba**
# Prework

- [x] I understand and agree to this repository's [code of conduct](https://github.com/ltelab/disdrodb/blob/main/CODE_OF_CONDUCT.md).
- [x] I understand and agree to this repository's [contributing guidelines](https://github.com/ltelab/disdrodb/blob/main/CONTRIBUTING.md).
- [x] I have already submitted an [issue](https://github.com/ltelab/disdrodb/issues) or [discussion thread](https://github.com/ltelab/disdrodb/discussions) to discuss my idea with the maintainers.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and communicate accordingly:

**The PR fulfills these requirements:**

- [x] It's submitted to the branch named as follow : 
  - Add a reader: `reader-<institute>-<campaign>`
  - Fix a bug: `bugfix-<some_key>-<word>`
  - Improve the doc: `doc-<some_key>-<word>`
  - Add a new feature: `feature-<some_key>-<word>`
  - Refactor some code: `refactor-<some_key>-<word>`
  - Optimize some code: `optimize-<some_key>-<word>`
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] Don't forget to link PR to issue if you are solving one.
- [x] All tests are passing.
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

# Related GitHub issues and pull requests

- [Pull-request comment](https://github.com/ltelab/disdrodb/pull/167#issuecomment-1488314185)

# Summary

## Main changes
- Add Ruff to CI
- Have lint run on every push
- Many files do not pass the pre-commit tests, currently

### CODE REVIEW

**Comment by regislon** [comment]
I think we should change the lines limits, what do you think @ghiggi ?

And do you have other inputs regarding ruff settings ?

**Comment by ghiggi** [comment]
@regislon I think we can increase slightly the line limits, but from what I saw in the Ruff CI what should be fixed are just a couple of docstrings (and maybe escape some lines with some special character when is not docstring)
If ruff complain about others rules, I suggest to 

1.  add those rules to the exceptions (maybe not the line length) in the pyproject.toml
2.  make pass the pre-commit and CI 
3.  then progressively adapt the code and exceptions to solve some of them
Also try to use `ruff --fix` to auto-fix some of them ([see configuration here](https://github.com/charliermarsh/ruff#configuration))

Maybe would be worth @sphamba to add also [blackdoc ](https://github.com/keewis/blackdoc) to the CI and recommit

**Review by ghiggi — APPROVED** [review]
LGTM. However, I noticed that the lint CI and precommit-CI still complains because of blackdoc on 
```
"error: cannot format /code/docs/source/readers.rst: Cannot parse: 54:22:     
"<DataSource1>": [<ReaderName1>, <ReaderName2>],"
```

Can you fix this error @sphamba?

**Comment by sphamba** [comment]
I am done!

**Comment by ghiggi** [comment]
@sphamba see comment above ... I edited

**Comment by sphamba** [comment]
@ghiggi Done! Note that all code (not marked as plain text) must be valid, so `<placeholders>` are not allowed in Python...

**Comment by sphamba** [comment]
@ghiggi Codecov and Coveralls are marked as fails. It seems that adding some line breaks increased the number of untested lines...

**Comment by ghiggi** [comment]
@sphamba thanks for all the work you made to put in place this really nice CI pipeline ;)

**Pull request merged**
